FROM node:18-alpine AS base
WORKDIR /app

ENV NODE_ENV=production

COPY package.json package-lock.json* ./
RUN npm install --production

COPY server ./server
COPY .env ./

EXPOSE 5000

CMD ["node", "server/index.js"]
